server.port=8081
spring.profiles.active=mongo
spring.thymeleaf.cache=false
spring.jackson.serialization.write-dates-as-timestamps=false
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/digital_evidence_2026}
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
logging.level.com.digitalevidence.mvc.mongodb=INFO
